<article>
	<div class="header">
		<span class="title">About Fudokan karate</span>
	</div><div class='image'><img src='/uploads/ilija.jpg'>
	</div><div class="text"><b>Prof. Ilija Jorga , founder of FUDOKAN - DO KARATE</b>
	<p>Before any other explanation I am obliged to clear some facts that are related to the  early beginning of Fudokan. From one unclear and foggy vision to the extremely serious  world institution. I can say freely that Fudokan symbolically has appeared in the  moment when I have entered the Dojo for the first time. In the beginning undetermined,  without almost no contours, amorphous, unclear and undetermined idea, thought  gradually has matured. Inside myself I have been caring a strong wish that the thing I do  be somehow different and certainly that had step by step developed and had greater complicity thru many years of hard training of all kind, competitions and friendship and communication with other karatekas during my lifetime.Karate club “Fudo” in Paris, that was the name of Dojo of my teacher Taiji Kase. Even today I still remember clearly of my first training in the mentioned Dojo, in early 70’is. 
	The part  of Fudokan probably originates from that time. On the other hand, Fudokan will grow in something much greater and higher then sentimental and beutiful memories. By random case or acto of destiny, I have combined the word Fudo with the word Kan and got a beautiful pair of word Fudokan.That hasn’t done by any Japanese, that was done by me, young, daring man, man from our region carried by vision.</p>
	
	<p>The 3 ideograms connected in the word Fudokan signifies : basis(base), home and foundation. Therefore the word Fudokan means : “House on stabile, solid, granite foundation.” In the case when the word Fudokan would be split and set in the form of Fu Do Kan it literally means Home Solid Home. Bit if the word Fudokan represents and certainly it cans for example like Fudo Kan, the thought is totally different. Then it takes deep, almost philosophical and ethical meaning which could be translated like “ immobile(real) wisdom”.</p>
	<p>The so called “Phenomenon of immobile wisdom” is the state that every truly Budoka prefers and strives with his complete existence. Not rarely the classics of Budo devote to it not at any coincidence, enormous attention and almost all teacher during history of fencing point out that it is a top that people strive to in the art of fighting. Modern top experts of Budo like for example Prof. T. Suzuki explains so called phenomenon of immobile wisdom by that that he equalizes it with mental stability. Simply, for him that’s the state when Budoka governs his emotions and doesn’t comply them with any external influence( for example when above you is a risen sword that is ready to cut you), your spirit is free and can freely find the best solution, undisturbed of emotions. Really, I couldn’t think of anything prettier, was it coincidence, certainly not! It doesn’t revolt me the surprise and certain dose of amazement when my dear friend H. Chirai asked me where did I come up with that beautiful name? Don’t forget, earlier before when a student would give to him Budo passport of Fudokan to him to sign, he would always throw it angry! Today when all those years have passed and when he realized all the glory of Fudokan, its irrefutable reality and dedication of its holders, he accepted it as normal appearance. That wasn’t by coincidence. Sensei Chirai, the famous and prestige name in the world of karate, rarely educated and intelligent man, the man of strong principles and very ambitious , as such has built a magnificent institution, not only in Italy(where he was located and lived), but in the whole world.He understand the deep meaning which in it carried the word, the ideogram of Fudokan. Constancy, honesty, loyalty, consistency to work and to teacher, where it is not possible to wonder off the path to the left or right carried by material interest and profane life. Fudokan hasn’t resist from its earliest beginnings till today to the infection of moral disfiguration, where betrayal, corruption and selling of positions were something, unfortunately usual in karate but for Fudokan unimaginable and completely foreign. That ugly, disfigurative and unmoral phenomenon is so often present in the world of karate and has taken its toll more and more. I must say that even in that time it was hard to resist to it, and it was only possible if the karateka had in him real strong moral values and woven ethical principles.</p>
	
	<p>The emblem of Fudokan has certain symbolic inter-connected with a lot of meanings, with a deep sense. On the shield of Fudokan the risen eagle is shown, then the sun, the tiger, the waves of ocean and finally the hundred years old trees. All is that shown on shield ,with a lot of meaning connected, so it easily recognizable to all who know at least a little about history of karate. To them it will be easy to see what is the meaning of Fudokan karate.The shield has double meaning : first it shows the connection of Fudokan and Budo tradition, the second by no doubt suggests on self defense, which is the essence of karate.</p>
	<p>The eagle risen above tiger which is set in the sun symbolicly shows the historical figure, the legendary Joshitaka Funakoshi, the genius of karate.</p>
	<p>The tiger(shoto) is a reincarnation of his father Gichin Funakoshi, the inventor of modern karate. There no comments are needed but setting the eagle above tiger was my wish that on some way, what is allowed to me, make historical mistake right!</p>
	
	<p> will remind you that in traditional Japan everything what was done, was credited to father, which is not rightand not true therefore that Joshitaka was truly the pioneer of traditional karate. Unfortunately, he died very young in the age of 35, but that didn’t bother him at all to leave an indelible trail in history of karate. On the left side of shield, the notched mane of tiger is spotted, which represents the branches of the hundred years old trees and basically picturesquely the waves of Pacific are present. By connecting the both symbols, message is obtained, the meaning, that is the doctrine is defined of Budo Karate of Fudokan which means : “ In the attack mightily like the waves of Pacific and in defense strong like a hundred years old trees!” I think that is not hard at all to recognize in this colorful, so warning and wordly doctrine the all together teachings of my teachers.</p>
	<p>The official foundation of Fudokan was delineated with the “small” ceremony, it was long ago in 1980.on 15th of November.By signing the Declaration of foundation of Fudokan by my oldest students, friends and like-minded people, the stamp was put and Fudokan set off into the world, truly in the beginning quietly without the big pomp. "</p>
	</div>
</article>